# Generated by Django 3.1 on 2020-08-29 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('job', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('AC', 'AC'), ('Electricity', 'Electicity'), ('Plumbing', 'Plumbing'), ('Wright Repair', 'Wright Repair'), ('Other', 'Other')], max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.orderworker')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('student_id', models.CharField(max_length=9, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('dorm', models.CharField(blank=True, choices=[('AA', 'AA'), ('BB', 'BB'), ('CC', 'CC'), ('DD', 'DD'), ('EE', 'EE'), ('FF', 'FF'), ('Gabriel V', 'Gabriel V'), ('Rosaria V', 'Rosaria V'), ('Aisha Kande', 'Aisha Kande')], max_length=50, null=True)),
                ('room', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='arab.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dorm', models.CharField(blank=True, choices=[('AA', 'AA'), ('BB', 'BB'), ('CC', 'CC'), ('DD', 'DD'), ('EE', 'EE'), ('FF', 'FF'), ('Gabriel V', 'Gabriel V'), ('Rosaria V', 'Rosaria V'), ('Aisha Kande', 'Aisha Kande')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Order Done', 'Order Done')], default='Pending', max_length=50, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('repair_date', models.CharField(blank=True, max_length=20, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student')),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.workorder')),
            ],
        ),
    ]
